from tkinter import*
root=Tk()
root.geometry("402x402+40+30")
root.resizable(True,False)
root.title("Calculator")
a=StringVar()
ent=Entry(root,font=('Arial',20,'bold'),bg='pink',fg='brown',textvariable=a)
ent.place(x=5,y=5,width=400,height=50)
#a=IntVar()
root.configure(bg='white')
def show(op):
    a.set(a.get()+op)
def eql():
    exp = a.get()
    try:
        a.set(eval(exp))
    except ZeroDivisionError:
        a.set("can't Devide by zero")
def clr():
    a.set(' ')
b1=Button(root,text='7',font=('Arial',20,'bold'),bg='lightblue',fg='white',activebackground='purple')
b1.place(x=5,y=55,width=100,height=50)
b1.configure(command=lambda:show("7"))
b2=Button(root,text='8',font=('Arial',20,'bold'),bg='lightblue',fg='white',activebackground='purple')
b2.place(x=100,y=55,width=100,height=50)
b2.configure(command=lambda:show("8"))
b3=Button(root,text='9',font=('Arial',20,'bold'),bg='lightblue',fg='white',activebackground='purple')
b3.place(x=200,y=55,width=100,height=50)
b3.configure(command=lambda:show("9"))
b4=Button(root,text='/',font=('Arial',20,'bold'),bg='black',fg='white',activebackground='purple')
b4.place(x=300,y=55,width=100,height=50)
b4.configure(command=lambda:show("/"))
b5=Button(root,text='4',font=('Arial',20,'bold'),bg='lightblue',fg='white',activebackground='purple')
b5.place(x=5,y=105,width=100,height=50)
b5.configure(command=lambda:show("4"))
b6=Button(root,text='5',font=('Arial',20,'bold'),bg='lightblue',fg='white',activebackground='purple')
b6.place(x=100,y=105,width=100,height=50)
b6.configure(command=lambda:show("5"))
b7=Button(root,text='6',font=('Arial',20,'bold'),bg='lightblue',fg='white',activebackground='purple')
b7.place(x=200,y=105,width=100,height=50)
b7.configure(command=lambda:show("6"))
b8=Button(root,text='*',font=('Arial',20,'bold'),bg='black',fg='white',activebackground='purple')
b8.place(x=300,y=105,width=100,height=50)
b8.configure(command=lambda:show("*"))
b9=Button(root,text='1',font=('Arial',20,'bold'),bg='lightblue',fg='white',activebackground='purple')
b9.place(x=5,y=155,width=100,height=50)
b9.configure(command=lambda:show("1"))
b10=Button(root,text='2',font=('Arial',20,'bold'),bg='lightblue',fg='white',activebackground='purple')
b10.place(x=100,y=155,width=100,height=50)
b10.configure(command=lambda:show("2"))
b11=Button(root,text='3',font=('Arial',20,'bold'),bg='lightblue',fg='white',activebackground='purple')
b11.place(x=200,y=155,width=100,height=50)
b11.configure(command=lambda:show("3"))
b12=Button(root,text='-',font=('Arial',20,'bold'),bg='black',fg='white',activebackground='purple')
b12.place(x=300,y=155,width=100,height=50)
b12.configure(command=lambda:show("-"))
b13=Button(root,text='C',font=('Arial',20,'bold'),bg='lightblue',fg='white',activebackground='purple')
b13.place(x=5,y=205,width=100,height=50)
b13.configure(command=lambda:clr())
b14=Button(root,text='=',font=('Arial',20,'bold'),bg='black',fg='white',activebackground='purple')
b14.place(x=100,y=205,width=100,height=50)
b14.configure(command=lambda:eql())
b15=Button(root,text='0',font=('Arial',20,'bold'),bg='black',fg='white',activebackground='purple')
b15.place(x=200,y=205,width=100,height=50)
b15.configure(command=lambda:show("0"))
b16=Button(root,text='+',font=('Arial',20,'bold'),bg='black',fg='white',activebackground='purple')
b16.place(x=300,y=205,width=100,height=50)
b16.configure(command=lambda:show("+"))
#but=Button(root,text='Click',font=('Arial',20,'bold'),bg='yellow',command=show)
#but.place(x=5,y=255,width=100,height=50)

mainloop()